
import { readFile, writeFile } from "node:fs/promises";

const DATA_PATH = "./public/data/contributions.json";
const README_PATH = "./README.md";
const SITE_URL = "https://madhav2348.github.io/my_contribution/";

function formatDate(iso) {
  return new Date(iso).toISOString().slice(0, 10);
}

function escapeCell(text) {
  return String(text).replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function buildReadme(payload) {
  const contributions = Array.isArray(payload.contributions) ? payload.contributions : [];
  const total = Number(payload.count ?? contributions.length);
  const username = payload.username ?? "unknown";
  const generatedAt = payload.generatedAt ?? new Date().toISOString();
  const latestMerge = contributions[0]?.date ?? null;

  const byRepo = new Map();
  for (const item of contributions) {
    const repo = item.project ?? "unknown/unknown";
    byRepo.set(repo, (byRepo.get(repo) ?? 0) + 1);
  }

  const uniqueRepos = byRepo.size;
  const topRepos = [...byRepo.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, 5);
  const recent = contributions;

  const topRepoLines =
    topRepos.length === 0
      ? "- No contributions found yet."
      : topRepos.map(([repo, count]) => `- \`${repo}\`: **${count}** merged PRs`).join("\n");

  const recentRows =
    recent.length === 0
      ? "| - | - | - |\n"
      : recent
          .map(
            (item) =>
              `| ${formatDate(item.date)} | \`${escapeCell(item.project)}\` | [${escapeCell(
                item.summary?.replace(/^Merged PR:\s*/i, "") ?? "PR",
              )}](${item.url}) |`,
          )
          .join("\n");

  return `# my_contribution

Auto-generated snapshot of merged pull requests by **${username}** to other people's repositories.

Live Site: ${SITE_URL}

## Contribution Overview

| Metric | Value |
| --- | ---: |
| Total merged PRs | ${total} |
| Unique repositories | ${uniqueRepos} |
| Last merged PR | ${latestMerge ? formatDate(latestMerge) : "-"} |
| Data generated at (UTC) | ${formatDate(generatedAt)} |

## Top Repositories

${topRepoLines}

## All Merged PRs

| Date (UTC) | Repository | Pull Request |
| --- | --- | --- |
${recentRows}

## Local Commands

\`\`\`bash
bun install
bun run refresh:contributions
bun run dev
\`\`\`

## GitHub Action

Run **Refresh Contributions JSON** from the Actions tab. It now updates both:

- \`public/data/contributions.json\`
- \`README.md\`

---

This README is generated by \`bun run generate:readme\`.
`;
}

async function run() {
  const raw = await readFile(DATA_PATH, "utf8");
  const payload = JSON.parse(raw);
  const readme = buildReadme(payload);
  await writeFile(README_PATH, readme, "utf8");
  console.log(`Updated ${README_PATH} from ${DATA_PATH}.`);
}

run().catch((error) => {
  console.error("Failed to generate README.");
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
